# Spring Application Configs
spring.application.name=portal
server.port=8080

# Spring Data MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/school_portal

# JWT Token Security Configs
school.app.jwtSecret=VedaSmartSchoolSecretKeySecuredByAntigravityDeepMindProject2026WithCustomLength
school.app.jwtExpirationMs=86400000

# Logging Levels for Clean Debugging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=INFO
